#!/bin/sh
### BEGIN INIT INFO
# Provides:          rfuse
# Required-Start:    
# Should-Start:      udev
# Required-Stop:     
# Default-Start:     S
# Default-Stop:
# Short-Description: Start and stop rfuse.
# Description:       Load the rfuse module and mount the rfuse control
#	filesystem.
### END INIT INFO

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
MOUNTPOINT=/sys/fs/rfuse/connections

# Gracefully exit if the package has been removed.
which rfusermount3 &>/dev/null || exit 5

# Define LSB log_* functions.
. /lib/lsb/init-functions

case "$1" in
    start|restart|force-reload)
	if ! grep -qw rfuse /proc/filesystems; then
		echo -n "Loading rfuse module"
		if ! modprobe rfuse >/dev/null 2>&1; then
			echo " failed!"
			exit 1
		else
			echo "."
		fi
	else
		echo "RFUSE filesystem already available."
	fi
	if grep -qw rfusectl /proc/filesystems && \
	   ! grep -qw $MOUNTPOINT /proc/mounts; then
		echo -n "Mounting rfuse control filesystem"
		if ! mount -t rfusectl rfusectl $MOUNTPOINT >/dev/null 2>&1; then
			echo " failed!"
			exit 1
		else
			echo "."
		fi
	else
		echo "RFUSE control filesystem already available."
	fi
	;;
    stop)
	if ! grep -qw rfuse /proc/filesystems; then
		echo "RFUSE filesystem not loaded."
		exit 7
	fi
	if grep -qw $MOUNTPOINT /proc/mounts; then
		echo -n "Unmounting rfuse control filesystem"
		if ! umount $MOUNTPOINT >/dev/null 2>&1; then
			echo " failed!"
		else
			echo "."
		fi
	else
		echo "RFUSE control filesystem not mounted."
	fi
	if grep -qw "^rfuse" /proc/modules; then
		echo -n "Unloading rfuse module"
		if ! rmmod rfuse >/dev/null 2>&1; then
			echo " failed!"
		else
			echo "."
		fi
	else
		echo "RFUSE module not loaded."
	fi
	;;
    status)
	echo -n "Checking rfuse filesystem"
	if ! grep -qw rfuse /proc/filesystems; then
		echo " not available."
		exit 3
	else
		echo " ok."
	fi
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
